from pathlib import Path

from datasets import load_dataset


def get_ground_truth(sample):
    assert sample["reward_model"]["ground_truth"] in sample["prompt"][0]["content"]
    sample["ground_truth"] = sample["reward_model"]["ground_truth"]
    sample.pop("prompt")
    sample.pop("reward_model")
    return sample


def merge_into_extra_info(sample):
    sample["extra_info"]["data_source"] = sample.pop("data_source")
    sample["extra_info"]["ability"] = sample.pop("ability")
    sample["extra_info"].pop("original_prompt", None)
    return sample


if __name__ == "__main__":
    # src_path = Path("/nfs/FM/chenshuailin/projects/kernel_agents/KernelGYM-vllm018-cuda-agent/drkernel/data/drkernel-rl-data-neutral/cuda_llm_rl_thinking_1025.parquet")
    # out_path = Path("data/drkernel-rl-data-0513.parquet")
    src_path = Path(
        "/nfs/FM/chenshuailin/projects/kernel_agents/KernelGYM-vllm018-cuda-agent/drkernel/data/kernelbench-level1-validation-neutral/validation_data_level1.parquet"
    )
    out_path = Path("data/kernelbench-level1-validation.parquet")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    ds = load_dataset("parquet", data_files=str(src_path), split="train")
    print(f"load from {src_path}")
    print(f"{len(ds)} samples, keys: {ds.column_names}")

    ds = ds.map(get_ground_truth)
    ds = ds.map(merge_into_extra_info)
    ds.to_parquet(str(out_path))
    print(f"save to {out_path}")

    # Formatted prompt review samples are generated by:
    #   pytest -s tests/utils/test_drkernel_prompt_templates.py
    # at checkpoints/drkernel_prompt_debug/formatted_prompt_examples.txt

    # try to load the saved dataset
    loaded = load_dataset("parquet", data_files=str(out_path), split="train")
    print(f"loaded from {out_path}")
    print(f"keys: {loaded.column_names}")
