CUDA_AGENT_CONFIGS = {
    "max_feedback_chars": 0,
    "log_multi_turn_sample_rate": 0.01,
    "log_slowest_step_window": 10,
    "log_slowest_min_delta_seconds": 5.0,
    "slowest_tracker_timeout": 2.0,
    "keep_history_thinking": True,
    # None: keep all generated turn samples; "positive": keep positive turns after a positive best reward;
    # "improve": keep only turns that improve the best reward after a positive best reward.
    "finalize_mode": "positive",
    "filter": {
        "reject_low_variance_groups": True,
        "reject_small_groups": True,
        "target_group_size": None,
        "min_group_size": None,
        "reward_std_threshold": 1e-3,
    },
    "multi_turn_prompt_config_path": "examples/kernel_agent/prompt_config/multi_turn_cuda_kernel.yaml",
    "kernel_backend": "cuda_agent",
    "reference_backend": "torch",
    "do_precheck": False,
    "env": {
        "kernel_eval_function_path": None,
        "kernel_eval_url": None,
        "kernel_eval_max_retries": 3,
        "kernel_eval_task_timeout": 300,
        "kernel_eval_client_timeout": 2400,
        "kernel_eval_poll_interval": 1.0,
        "kernel_eval_heartbeat_interval": 60.0,
        "kernel_eval_worker_max_concurrency": 32,
        "kernel_eval_rate_limit": 32,
        "kernel_eval_acquire_timeout": 2400,
        "num_correct_trials": 5,
        "num_perf_trials": 100,
        "verbose_errors": True,
        "enable_profiling": True,
        "detect_decoy_kernel": True,
        "split_compile_and_execute": True,
        "enable_compile_artifact_cache": True,
    },
    "reward": {
        "multi_turn_gamma": 1.0,
        "init_correct_weight": 0.5,
        "init_performance_weight": 0.5,
        "speedup_reward_upper_bound": 3.0,
        "speedup_reward_lower_bound": 0.0,
        "penalty_score": -0.5,
        "compilation_fail_penalty": -0.2,
        "precheck_fail_penalty": -0.5,
        "apply_compilation_fail_penalty": True,
        "apply_precheck_fail_penalty": True,
        "coverage_reward_enable": True,
        "coverage_reward_type": "time_coverage",
        "coverage_reward_weight": 0.5,
    },
}
